apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-producer
  namespace: smart-parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-producer
  template:
    metadata:
      labels:
        app: iot-sensor-producer
    spec:
      containers:
        - name: iot-sensor-producer
          image: iot-sensor-producer:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: iot-sensor-producer
  namespace: smart-parking
spec:
  selector:
    app: iot-sensor-producer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iot-sensor-producer-hpa
  namespace: smart-parking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iot-sensor-producer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
