apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-api-gateway
  namespace: smart-parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-api-gateway
  template:
    metadata:
      labels:
        app: driver-api-gateway
    spec:
      containers:
        - name: driver-api-gateway
          image: driver-api-gateway:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: driver-api-gateway
  namespace: smart-parking
spec:
  selector:
    app: driver-api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
