apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-controller
  namespace: smart-parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-controller
  template:
    metadata:
      labels:
        app: parking-controller
    spec:
      containers:
        - name: parking-controller
          image: parking-controller:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/smart_parking
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: parking-controller
  namespace: smart-parking
spec:
  selector:
    app: parking-controller
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
