apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-generator
  namespace: smart-parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-generator
  template:
    metadata:
      labels:
        app: alert-generator
    spec:
      containers:
        - name: alert-generator
          image: alert-generator:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/smart_parking
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: alert-generator
  namespace: smart-parking
spec:
  selector:
    app: alert-generator
  ports:
    - port: 8083
      targetPort: 8083
